### ISSUE TITLE
Navbar KHÔNG drop down được 

### ISSUE THREAD

**Issue by GS-755** [phathung2003/DATN-QuanLyHocTap#4]
**Vấn đề: Navbar KHÔNG dropdown được**
**Nguyên nhân: không rõ (có thể do thiếu event hoặc template bị lỗi sau khi merge vào dự án)**
Giải pháp tạm thời: Comment dữ liệu của dropdown để ẩn đi 

https://github.com/user-attachments/assets/59fd5372-76de-4d49-bb02-7176644be930

**Comment by Thanhle-18092003** [comment]
nớp phần Navbar drop down

**Comment by GS-755** [comment]
> nớp phần Navbar drop down

Kiểm tra source code tại branch master xem phần dropdown đã mất chưa, 
Sau đó sao lưu code cái dropdown navbar đó để khi cần thì có cái để tham khảo, và khi có source code thì fix xung đột thư viện frontend dễ cũng như là có ngay nguồn code để tham khảo nha @Thanhle-18092003
